### PR TITLE
Send done after 10s when showing as placeholder

### PR DESCRIPTION
**Pull request by ezequielc**
## Description
Send done after 10s when showing as placeholder

## Motivation and Context
Playlist UI epic - Playlist rendering

## How Has This Been Tested?
https://apps-stage-12.risevision.com/templates/edit/2421060d-a33b-4ffe-a1bc-ba1f788c0469/?cid=554d3ef9-78b7-4726-8f46-c1ec140c166d

## Release Plan:
- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed. 
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed

#### Release Checklist Items Skipped?
If any Release Checklist items were intentionally skipped, please provide which ones and the reasons why

### CODE REVIEW

**Review by alex-deaconu — APPROVED** [review]
@ezequielc looks good 👍

**Comment by ezequielc** [comment]
@stulees @olegrise As per [this doc](https://docs.google.com/document/d/1W9-pnI1GA9rXhr21sZn4-zme075BR9SiBvVu9Vf59Cw/edit#heading=h.ohawbyvl0ncb), I am sending a Done event 10s after placeholder is shown, so that we don't have issues with playlists in the Editor.
In addition, I updated the placeholder style to match the current style of playlists placeholder. Please review. Thanks

**Review by stulees — CHANGES_REQUESTED** [review]
@ezequielc Can you bump the version of the component in `package.json`. I think it warrants a feature bump, so it should now be `1.2.0`. Thanks

**Comment by ezequielc** [comment]
@stulees Sounds good, will do that. Thanks

**Comment by olegrise** [comment]
Looks good to me.

**Comment by ezequielc** [comment]
@stulees I bumped the version for this as per request. This is ready to be released. Please review. Thanks!

**Review by stulees — APPROVED** [review]

**Pull request merged**
