### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by willread**
## Description
Bumping the version number so I can tag a release.

## Motivation and Context
I would like to tag this release to simplify rollback if needed.

## How Has This Been Tested?
No testing required.

## Release Plan:
- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed. 
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed

#### Release Checklist Items Skipped?

No applicable items have been skipped.

### CODE REVIEW

**Comment by willread** [comment]
@santiagonoguez I made that change to the circleci config.

**Comment by santiagonoguez** [comment]
thanks !

**Comment by stulees** [comment]
@willread @santiagonoguez Are we tagging releases now? Not sure what use that will be since we target static URLs in templates. Can you clarify, thanks

**Comment by santiagonoguez** [comment]
@stulees just to follow the changes on rise-image, or do you prefer us to wait until it's in production ? @willread

**Comment by stulees** [comment]
@santiagonoguez I'm fine either way, I was just wondering if you feel its beneficial to tag a release. Even though we won't target a release as a dependency in package.json, perhaps its good to see a release history of changes.

**Pull request merged**
